### PR TITLE
Present the ImageScannerController modally to prevent invisible nav bar

### PR DESCRIPTION
**Pull request by sjoness**
This fixes an issue when presenting the `ImageScannerController` modally. The partial takeover has a transparent nav bar and therefore you can see the `UINavigationController` underneath and the `UIBarButtonItem`s are not clearly visible.

By presenting the view controllers with fullscreen modal presentation style, the nav bar is forced black and the text is legible

### Before

IMG_1831

### After

IMG_1832
IMG_1833
IMG_1834

### CODE REVIEW

**Comment by cansavrun** [comment]
Hi,I did what you did but my nav bar still like the first image?

**Comment by kalloszsolty** [comment]
Tested it, indeed fixes the issue on iOS too. Better than before. Would love this to be merged ASAP.
Besides this, there's one innocent problem that still happens, somehow the screen is not fully overlayed and if I try to press the screen area where the camera/gallery select buttons should be, I get the events in the log:
`[Presentation] Attempt to present <UIImagePickerController: 0x10b016400> on <FlutterViewController: 0x10200fa00> (from <FlutterViewController: 0x10200fa00>) whose view is not in the window hierarchy.`

**Review by kalloszsolty — APPROVED** [review]

**Comment by kalloszsolty** [comment]
Until it's merged, using this branch in the app like:
`  document_scanner_flutter:
    git:
      url: git://github.com/sjoness/document_scanner_flutter.git
      ref: fix/scanner-transparent-nav-bar`

**Comment by ishaquehassan** [comment]
@kalloszsolty Merged thanks <3

**Comment by Tabarek** [comment]
This issue exists in editing scanned screen after picking a gallery image!!

**Comment by jason45992** [comment]
> This issue exists in editing the scanned screen after picking a gallery image!!

+1

**Comment by jprobert** [comment]
> This issue exists in editing the scanned screen after picking a gallery image!!

+1

**Comment by Richard-DEPIERRE** [comment]
> This issue exists in editing the scanned screen after picking a gallery image!!

+1

**Comment by Ludwigvsch** [comment]
Although I have the newest version of the plugin, it still is transparent for me on the ios simulator. Can someone please help? 
Thank you

**Pull request merged**
